name: Atualizar Mancha Criminal NOD
on:
schedule:
# Roda toda segunda-feira às 05:00 da manhã
- cron: '0 5 * * 1'
workflow_dispatch:
jobs:
build:
runs-on: ubuntu-latest
env:
ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
code
Code
steps:
- name: Checkout do código
  uses: actions/checkout@v4

- name: Configurar Python
  uses: actions/setup-python@v5
  with:
    python-version: '3.10'

- name: Instalar dependências
  run: |
    pip install pandas requests

- name: Processar Dados do ISP
  run: python processar_isp.py

- name: Enviar JSON via Ponte PHP
  run: |
    curl -X POST "http://nod.22web.org/receber_json.php?token=o79yYceXux" \
         -H "Content-Type: application/json" \
         --data-binary @isp_crime_stats.json
